server:
  port: 5000

db:
  host: 'korea-webtoon-review.herokuapp.com'
  # username: 'root'
  # password: 'root'
  username: 'JooChunWook'
  password: 'tQLW2seVmA50ylEY'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'Secret1234'
